In [1]:
import numpy as np

def least_cost_method(cost_matrix, supply, demand):
    rows, cols = len(supply), len(demand)
    allocation = np.zeros((rows, cols))
    
    while sum(supply) > 0 and sum(demand) > 0:
        # Find the cell with the minimum cost
        min_cost = float('inf')
        min_cell = (0, 0)
        for i in range(rows):
            for j in range(cols):
                if cost_matrix[i][j] < min_cost and supply[i] > 0 and demand[j] > 0:
                    min_cost = cost_matrix[i][j]
                    min_cell = (i, j)
        
        i, j = min_cell
        
        # Allocate resources
        allocation[i][j] = min(supply[i], demand[j])
        allocation_value = allocation[i][j]
        
        # Update supply and demand
        supply[i] -= allocation_value
        demand[j] -= allocation_value
    
    return allocation

def calculate_total_cost(cost_matrix, allocation):
    total_cost = 0
    rows, cols = allocation.shape
    for i in range(rows):
        for j in range(cols):
            total_cost += allocation[i][j] * cost_matrix[i][j]
    return total_cost

# Example usage
cost_matrix = [
    [190, 300, 500, 100],
    [700, 300, 400, 600],
    [400, 100, 400, 200],
]

supply = [70, 90, 180]
demand = [50, 80, 70, 140]


allocation = least_cost_method(cost_matrix, supply, demand)
total_cost = calculate_total_cost(cost_matrix, allocation)

print("Allocation matrix:")
print(allocation)
print(f"Total Transportation Cost: {total_cost}")


Allocation matrix:
[[ 0.  0.  0. 70.]
 [20.  0. 70.  0.]
 [30. 80.  0. 70.]]
Total Transportation Cost: 83000.0
