In [1]:
import numpy as np

In [2]:
ar = np.array([10,20,30,40,50,60])
print(ar)

[10 20 30 40 50 60]


In [3]:
ar.dtype

dtype('int64')

In [4]:
n = np.zeros(5)
print(n)

[0. 0. 0. 0. 0.]


In [5]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])